info:
  version: 1.0.3
  description: CHF initial local configuration

configuration:
  chfName: CHF
  sbi:
    scheme: http
    registerIPv4: chf
    bindingIPv4: 0.0.0.0
    port: 8000
    tls:
      pem: cert/chf.pem
      key: cert/chf.key
  nrfUri: http://nrf:8000
  nrfCertPem: cert/nrf.pem
  serviceNameList:
    - nchf-convergedcharging
  mongodb:
    name: free5gc
    url: mongodb://db:27017
  quotaValidityTime: 10000
  volumeLimit: 50000
  volumeLimitPDU: 10000
  volumeThresholdRate: 0.8
  cgf:
    enable: false
    hostIPv4: 127.0.0.1
    port: 2121
    listenPort: 2122
    passiveTransferPortRange:
      start: 2123
      end: 2130
    tls:
      pem: cert/chf.pem
      key: cert/chf.key
    cdrFilePath: /tmp
  abmfDiameter:
    protocol: tcp
    hostIPv4: 0.0.0.0
    port: 3868
    tls:
      pem: cert/chf.pem
      key: cert/chf.key
  rfDiameter:
    protocol: tcp
    hostIPv4: 0.0.0.0
    port: 3869
    tls:
      pem: cert/chf.pem
      key: cert/chf.key

logger:
  enable: true
  level: info
